Feature/srytal be 37
yadagiritalada143/SRYTAL-BE pull request #62
Opened 2024-10-03 18:52 UTC by Ramyathummala

Implement API to Get all employee details by Super Admin #37

2024-10-05 17:12 UTC, yadagiritalada143 requested changes

2024-10-05 17:12 UTC, yadagiritalada143 commented on src/controllers/superAdmin/getAllEmployeesBySuperAdminController.ts
> +import { error } from "console";
This is resolved.

2024-10-07 18:16 UTC, Ramyathummala commented on src/constants/commonErrorMessages.ts
> +    FETCHING_ALLEMPLOYEE_ERROR:'An error occurred while fatching allemployeebysuperadmin ! '
This is resolved

2024-10-07 18:37 UTC, Ramyathummala commented on src/controllers/superAdmin/getAllEmployeesBySuperAdminController.ts
> +import { error } from "console";
This is resolved

2024-10-07 18:38 UTC, Ramyathummala commented on src/controllers/superAdmin/getAllEmployeesBySuperAdminController.ts
> +export default {getAllEmployeesBySuperAdmin}
Reloved this

2024-10-07 18:38 UTC, Ramyathummala commented on src/services/superAdmin/getAllEmployeesBySuperAdminService.ts
> +// interface FetchUserResponse {
Resolved this

2024-10-07 18:39 UTC, Ramyathummala commented on src/routes/superAdminRoutes.ts
> +
This is resolved

2024-10-07 18:39 UTC, Ramyathummala commented on src/controllers/superAdmin/getAllEmployeesBySuperAdminController.ts
> +const getAllEmployeesBySuperAdmin=(req:Request,res:Response)=>{
Resolved this

2024-10-07 18:40 UTC, Ramyathummala commented on src/controllers/superAdmin/getAllEmployeesBySuperAdminController.ts
> +import { error } from "console";
This is resolved

2024-11-09 09:53 UTC, merged